-- One row per game session (practice, qualifying, race, time trial run, ...).
create table session
(
    -- F1 m_sessionUID. The game sends an unsigned 64-bit value; it is stored as its signed 64-bit
    -- bit pattern and converted back to the unsigned decimal form at the API boundary.
    session_uid     bigint primary key,
    session_type    integer     not null, -- spec appendix "Session types"
    track_id        integer     not null, -- spec appendix "Track IDs" (-1 = unknown)
    track_length_m  integer,
    sector2_start_m real,                 -- lap distance where sector 2 / 3 begin
    sector3_start_m real,
    weekend_link_id bigint      not null default 0,
    game_mode       integer,
    formula         integer,
    started_at      timestamptz not null
);

-- One row per completed lap of the player's car. Laps are identified by their lap number within the
-- session, exactly like the game's own Session History.
create table lap
(
    id           bigint generated by default as identity primary key,
    session_uid  bigint      not null references session (session_uid) on delete cascade,
    lap_number   integer     not null,
    lap_time_ms  integer     not null,
    sector1_ms   integer,
    sector2_ms   integer,
    sector3_ms   integer,
    valid        boolean     not null,
    pit_in       boolean     not null, -- lap ended in the pit lane (in-lap)
    pit_out      boolean     not null, -- lap started in the pit lane (out-lap)
    sample_count integer     not null,
    recorded_at  timestamptz not null,
    constraint uq_lap_session_lap_number unique (session_uid, lap_number)
);

-- The lap's telemetry, stored column-wise: one array per channel ("distance", "time", "speed", ...),
-- all the same length and index-aligned (samples[i] of every channel belong to the same frame).
-- A lap is always written once and read as a whole, so this is one small row per channel instead of
-- thousands of per-sample rows, and adding a channel later needs no schema change.
create table lap_channel
(
    lap_id  bigint      not null references lap (id) on delete cascade,
    channel varchar(32) not null,
    samples real[]      not null,
    primary key (lap_id, channel)
);
